parameters:
    doctrine.class: ArcaSolutions\MultiDomainBundle\Doctrine\DoctrineRegistry
    domain.listener.class: ArcaSolutions\MultiDomainBundle\EventListener\DomainListener
    domain.information.class: ArcaSolutions\MultiDomainBundle\Services\Settings
    domain.locale.class: ArcaSolutions\MultiDomainBundle\EventListener\LocaleListener
    domain.database.class: ArcaSolutions\MultiDomainBundle\EventListener\DatabaseListener

services:
    multi_domain.domain_listener:
        class: %domain.listener.class%
        arguments: ["@service_container"]
        public: true
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 1000 }

    database.domain_listener:
        class: %domain.database.class%
        arguments: [@service_container, @doctrine.dbal.domain_connection]
        scope: request
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    multi_domain.information:
        class: %domain.information.class%
        arguments: ["@service_container", %multi_domain.config%]
