<?php

namespace ArcaSolutions\ClassifiedBundle\Repository;

use ArcaSolutions\CoreBundle\Repository\EntityLocationRepository;

/**
 * ClassifiedLocationcounter
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassifiedLocationcounterRepository extends EntityLocationRepository
{
}
