<?php

namespace ArcaSolutions\ClassifiedBundle\Repository;

use ArcaSolutions\CoreBundle\Repository\EntityCategoryRepository;

/**
 * Classifiedcategory
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassifiedcategoryRepository extends EntityCategoryRepository
{
    /**
     * {@inheritdoc}
     */
    public function getParentCategories($limit = null, $featured = true)
    {
        $this->setMaxItems($limit);
        $this->setActiveItemsNameField('activeClassified');

        return parent::getParentCategories($featured);
    }

    /**
     * @param int $limit
     *
     * @return array
     */
    public function getPopularCategories($limit = null)
    {
        return $this->createQueryBuilder('q')
            ->andWhere('q.enabled = :enabled')
            ->andWhere('q.activeClassified > :active')
            ->setParameter('enabled', 'y')
            ->setParameter('active', 0)
            ->orderBy('q.activeClassified', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
