<?php

namespace ArcaSolutions\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CheckinRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CheckinRepository extends EntityRepository
{
    /**
     * @param int    $id
     * @param string $module [listing|event]
     *
     * @return array
     */
    public function getTotalByItemId($id, $module)
    {
        return $this->createQueryBuilder('r')
            ->select('count(r.id)')
            ->where('r.itemType = :module')
            ->andWhere('r.itemId = :id')
            ->setParameter('module', $module)
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
