<?php

namespace ArcaSolutions\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SettingLocationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SettingLocationRepository extends EntityRepository
{
    /**
     * Returns ids of enabled locations
     *
     * @return array
     */
    public function getLocationsEnabledID()
    {
        $locations = $this->findBy(['enabled' => 'y'], ['id' => 'ASC']);
        $ids = [];
        foreach ($locations as $loc) {
            $ids[] = $loc->getId();
        }

        return $ids;
    }

    public function getLastLocationEnabledID()
    {
        $location = $this->findOneBy(['enabled' => 'y'], ['id' => 'DESC']);

        if ($location) {
            return $location->getId();
        }

        return null;
    }
}
