event_homepage:
    path:     /
    defaults: { _controller: EventBundle:Default:index }

event_allcategories:
    path:     /%alias_event_allcategories_url_divisor%
    defaults: { _controller: EventBundle:Default:allcategories }

event_alllocations:
    path:     /%alias_alllocations_url_divisor%
    defaults: { _controller: EventBundle:Default:alllocations }

event_sample:
    path:     /{friendlyUrl}-{level}.{_format}
    defaults: { _controller: EventBundle:Default:sampleDetail }
    requirements:
        friendlyUrl: "sample"
        level: \d+
        _format:  html

event_detail:
    path:     /{friendlyUrl}.{_format}
    defaults: { _controller: EventBundle:Default:detail }
    requirements:
        _format:  html

event_calendar:
    path:     /calendar/{month}/{year}
    defaults: { _controller: EventBundle:Calendar:calendar }
    condition: "request.isXmlHttpRequest()"
    requirements:
        month:  \d+
        year:   \d+
    options:
        expose: true

event_upcoming:
    path:     /upcoming/{day}/{month}/{year}
    defaults: { _controller: EventBundle:Calendar:upcoming }
    condition: "request.isXmlHttpRequest()"
    requirements:
        day:    \d+
        month:  \d+
        year:   \d+
    options:
        expose: true

event_sendmail:
    path:     /sendmail/{id}
    defaults: { _controller: WebBundle:SendMail:index, module: event }
    requirements:
            id: \d+

event_checkin:
    path:     /checkins/{friendlyUrl}/{page}
    defaults: { _controller: EventBundle:Default:checkin, page: 1 }
    requirements:
        page: \d+
