<?php

namespace ArcaSolutions\ListingBundle\Repository;

use ArcaSolutions\CoreBundle\Repository\EntityLocationRepository;

/**
 * ListingLocationcounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingLocationcounterRepository extends EntityLocationRepository
{
}
