parameters:
    twig_extension.image.class: 'ArcaSolutions\ImageBundle\Twig\Extension\ImageExtension'
    image.handler.class: ArcaSolutions\ImageBundle\Services\ImageHandler

services:
    image.twig_extension:
        class: %twig_extension.image.class%
        public: false
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    imagehandler:
        class: %image.handler.class%
        arguments: [@service_container]
