<?php

namespace ArcaSolutions\BlogBundle\Repository;

use ArcaSolutions\CoreBundle\Repository\EntityCategoryRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogcategoryRepository extends EntityCategoryRepository
{
    /**
     * {@inheritdoc}
     */
    public function getParentCategories($limit = null, $featured = true)
    {
        $this->setMaxItems($limit);
        $this->setActiveItemsNameField('activePost');

        return parent::getParentCategories($featured);
    }
}
