<?php

namespace ArcaSolutions\DealBundle\Repository;

use ArcaSolutions\CoreBundle\Repository\EntityLocationRepository;

/**
 * PromotionLocationcounter
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionLocationcounterRepository extends EntityLocationRepository
{
}
