# SearchBundle Elasticsearch Servers
search:
    elasticsearch:
        servers:
            server1:
                host: "%elastic_host%"
                port: "%elastic_port%"
#            server2:
#                host: ''
#                port: 9200
    settings:
        randomizationInterval: "20 minutes"
        defaultSearchResultSize: 10
        locationUnit: "mi"
    map:
        icons:
            iconPath: "assets/icons/"
            classified: "classified.svg"
            deal: "deal.svg"
            event: "event.svg"
            listing: "listing.svg"
            group:
                url: "pin.svg"
                textColor: "#FFFFFF"
                height: 39
                width: 39
    seo:
        friendlyUrlOrder: ["module", "category", "location", "keyword", "startDate", "endDate"]
