<?php

namespace ArcaSolutions\BannersBundle\Repository;

use ArcaSolutions\BannersBundle\Entity\Banner;
use ArcaSolutions\BannersBundle\Entity\Bannerlevel;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\OptimisticLockException;


/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository
{
    /**
     * Description
     *
     * @param Bannerlevel $level
     * @param array|null $categorizedSections
     * @return Banner|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getBanner($level, $categorizedSections = [])
    {
        static $usedBanners = [];

        $categorizedSections or $categorizedSections["general"] = null;

        $return = null;

        if ($level) {
            $qb = $this->createQueryBuilder('b');

            $mainConditional = $qb->expr()->andX();

            $qb->setParameters([
                'impression'  => 1,
                'unlimited'   => 'y',
                'renewalDate' => 2,
                'global'      => 'global',
                'status'      => 'A',
                'type'        => $level->getValue()
            ]);

            /* Limited impressions expiration conditional */
            $condExpirationImpressions = $qb->expr()->andX()->addMultiple([
                $qb->expr()->eq('b.expirationSetting', ':impression'),
                $qb->expr()->gt('b.impressions', 0),
            ]);

            /* Unlimited impressions expiration conditional */
            $condExpirationUnlimited = $qb->expr()->andX()->addMultiple([
                $qb->expr()->eq('b.expirationSetting', ':impression'),
                $qb->expr()->eq('b.unlimitedImpressions', ':unlimited'),
            ]);

            /* Time expiration conditional */
            $temporalExpirationCondition = $qb->expr()->andX()->addMultiple([
                $qb->expr()->eq('b.expirationSetting', ':renewalDate'),
                $qb->expr()->gte('b.renewalDate', 'CURRENT_DATE()'),
            ]);

            /* Combined expiration conditions */
            $mainConditional->add(
                $qb->expr()->orX()->addMultiple([
                    $temporalExpirationCondition,
                    $condExpirationImpressions,
                    $condExpirationUnlimited,
                ])
            );

            /* Section and category conditionals */
            if ($categorizedSections) {
                $condSection = $qb->expr()->orX();
                $condSection->add($qb->expr()->eq('b.section', ':global'));

                $i = 0;
                $j = 0;

                foreach ($categorizedSections as $section => $categories) {
                    if ($categories) {
                        $secondCondition = $qb->expr()->in('b.categoryId', ":category{$j}");
                        $qb->setParameter("category{$j}", (array)$categories);
                        $j++;
                    } else {
                        $secondCondition = $qb->expr()->eq('b.categoryId', ":nocategory");
                        $qb->setParameter("nocategory", 0);
                    }

                    $condSection->add($qb->expr()->andX()->addMultiple([
                        $qb->expr()->eq('b.section', ":section{$i}"),
                        $secondCondition,
                    ]));

                    $section == "deal" and $section = "promotion";
                    $qb->setParameter("section{$i}", $section);
                    $i++;
                }
            } else {
                $condSection = $qb->expr()->eq('b.section', ':global');
            }

            $mainConditional->add($condSection);

            /* Repeated banner exclusion conditional */
            if ($usedBanners) {
                $mainConditional->add($qb->expr()->notIn('b.id', ":ids"));
                $qb->setParameter('ids', array_keys($usedBanners));
            }

            /* Basic conditionals */
            $mainConditional->addMultiple([
                $qb->expr()->eq('b.status', ':status'),
                $qb->expr()->eq('b.type', ':type')
            ]);

            $qb->where($mainConditional);

            $banner = $qb->addSelect('RAND() as HIDDEN rand')->setMaxResults(1)->orderBy('rand')->getQuery();

            if ($return = $banner->getOneOrNullResult()) {
                /* @var $return Banner */
                $usedBanners[$return->getId()] = true;
            }
        }

        return $return;
    }

    /**
     * Subtracts Impressions
     *
     * @param Banner $banner
     * @return bool
     */
    public function setImpression(Banner $banner)
    {
        try {
            $banner->setImpressions(max([($banner->getImpressions() - 1), 0]));
        } catch (OptimisticLockException $e) {
        }
    }
}
