<?php

namespace ArcaSolutions\EventBundle\Repository;

use ArcaSolutions\CoreBundle\Repository\EntityCategoryRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventcategoryRepository extends EntityCategoryRepository
{
    /**
     * {@inheritdoc}
     */
    public function getParentCategories($limit = null, $featured = true)
    {
        $this->setMaxItems($limit);
        $this->setActiveItemsNameField('activeEvent');

        return parent::getParentCategories($featured);
    }
}
