<?php

namespace ArcaSolutions\EventBundle\Repository;

use ArcaSolutions\CoreBundle\Repository\EntityLocationRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventLocationcounterRepository extends EntityLocationRepository
{
}
